### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by wand09** [Pipetto-crypto/3in1ProotX86Emus#1]
hello brother, I want to ask.  is this a kind of Box64droid/termux box?  I have tried installing it.  but I don't know the command/way to enter Windows

**Comment by Pipetto-crypto** [comment]
To enter you can type winedesktop.

It's like Termux-box, Box64droid but it's totally native so it can be potentially faster

**Comment by wand09** [comment]
> To enter you can type winedesktop.
> 
> It's like Termux-box, Box64droid but it's totally native so it can be potentially faster

**Comment by wand09** [comment]
Thank you for the answer bro, I wanted to ask.  Can disks C, D and Z not be displayed when opening TFM?

**Comment by Pipetto-crypto** [comment]
> Thank you for the answer bro, I wanted to ask. Can disks C, D and Z not be displayed when opening TFM

I don't know I have never used TFM, and the default of this project is 7zFM

**Comment by kimaiden1408** [comment]
Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76)
It shows me error messages try with box86

**Comment by Pipetto-crypto** [comment]
> Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76) It shows me error messages try with box86

That's not an error so ignore it. But no mali doesn't work yet but will in the future.

**Comment by kimaiden1408** [comment]
Thanks for answering my question. Hope mali will be featured soon!~

**Comment by wand09** [comment]
> > Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76) It shows me error messages try wit


> > Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76) It shows me error messages try with box86
> 
> That's not an error so ignore it. But no mali doesn't work yet but will in the future.

![Screenshot_2023-10-31-17-37-52-291_com termux](https://github.com/Pipetto-crypto/androBox/assets/39123207/153f60d1-cb3a-4d5f-8bef-8dca9c40d244)

Why i can't use Dxvk ?

**Comment by Pipetto-crypto** [comment]
> > > Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76) It shows me error messages try wit
> 
> > > Hi, Is AndroBox compatible with mali gpus? (Mine is mali-G76) It shows me error messages try with box86
> > 
> > 
> > That's not an error so ignore it. But no mali doesn't work yet but will in the future.
> 
> ![Screenshot_2023-10-31-17-37-52-291_com termux](https://user-images.githubusercontent.com/39123207/279346180-153f60d1-cb3a-4d5f-8bef-8dca9c40d244.jpg)
> 
> Why i can't use Dxvk ?

Are you using fdroid termux? In any case, try pkg update && pkg upgrade

**Comment by aaa-sys-potato** [comment]
Can you specify when mali devices will be supported?

**Comment by wand09** [comment]
![Screenshot_2023-10-31-18-40-29-090_com termux x11](https://github.com/Pipetto-crypto/androBox/assets/39123207/a14063fd-b1d1-4fe8-85cb-bb9b3f129927)

Thank you bro, well this is what I meant to my previous question.  7zfm not showing disk C,D,Z ?  is it really like this?

**Comment by Pipetto-crypto** [comment]
> ![Screenshot_2023-10-31-18-40-29-090_com termux x11](https://user-images.githubusercontent.com/39123207/279363882-a14063fd-b1d1-4fe8-85cb-bb9b3f129927.jpg)
> 
> Thank you bro, well this is what I meant to my previous question. 7zfm not showing disk C,D,Z ? is it really like this?

Nope but it can be fixed from Start Menu:

Update->Prefix
Configure->repairsettings
Wine->resetpfx

**Comment by Pipetto-crypto** [comment]
> Can you specify when mali devices will be supported?

Probably by the first week of November

**Comment by wand09** [comment]
> > Can you specify when mali devices will be supported?
> 
> Probably by the first week of November

bro, is the box native supported  dri3 ?  and can use messa turnip?

**Comment by Bububgithub** [comment]
what is the command to exit.?

**Comment by wand09** [comment]
> what is the command to exit.?

Shutdown  on windows

**Comment by Maks48rus** [comment]
can't install, do I need root to install?

**Comment by Maks48rus** [comment]
what to do?

1.Wine 8.0 Stable(Adreno 7xx users recommended)            2.Wine 8.14 Devel                                                                                                     Select a wine version to install:mv: cannot stat '/data/data/com.termux/files/usr/glibc/opt/wine-*-amd64': No such file or directory                                             Cloning into 'androBox'...
remote: Enumerating objects: 2162, done.                   remote: Counting objects: 100% (474/474), done.            remote: Compressing objects: 100% (308/308), done.         remote: Total 2162 (delta 272), reused 319 (delta 149), pack-reused 1688                                              Receiving objects: 100% (2162/2162), 13.35 MiB | 1.66 MiB/s, done.                                                    Resolving deltas: 100% (1208/1208), done.                  /data/data/com.termux/files/usr/bin/wine: line 9: 26317 Killed                  termux-x11 > /dev/null 2>&1
Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead                                                          wine: configuration in L"/home/.wine" has been updated.    Cloning into 'androBox'...                                 remote: Enumerating objects: 2162, done.
remote: Counting objects: 100% (474/474), done.            remote: Compressing objects: 100% (308/308), done.         remote: Total 2162 (delta 272), reused 319 (delta 149), pack-reused 1688                                              Receiving objects: 100% (2162/2162), 13.35 MiB | 1.75 MiB/s, done.                                                    Resolving deltas: 100% (1208/1208), done.                  ~ $ winedesktop                                            /data/data/com.termux/files/usr/bin/winedesktop: line 7: 29931 Killed                  termux-x11 > /dev/null 2>&1    Can't open display :0                                      /data/data/com.termux/files/usr/bin/wine: line 9: 30046 Killed                  termux-x11 > /dev/null 2>&1           Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead

>

**Comment by Belorr** [comment]
~ $ winedesktop                                   
Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead

**Comment by aaa-sys-potato** [comment]
It's mali supported now?
