### ISSUE TITLE
Call of Duty 2 mouse capture issue.

### ISSUE THREAD

**Issue by pablo19989898** [Pipetto-crypto/3in1ProotX86Emus#11]
Call of Duty 2 messing with mouse capture and even not recognizing wsad keys through InputBridge. Please help and answer :)

**Comment by Pipetto-crypto** [comment]
Try to mess with mouse warp override:

Start Menu->Registry->MouseWarpOverride

**Comment by pablo19989898** [comment]
Tried that + change in regedit , nothing works.

**Comment by Pipetto-crypto** [comment]
> Tried that + change in regedit , nothing works.

![Uploading Schermata_del_2023-11-08_18-49-46.png…]()
 
I tried the demo and works okay for me

**Comment by Pipetto-crypto** [comment]
> Tried that + change in regedit , nothing works.

I just tried the demo and works okay for me
![Uploading Screenshot_2023-11-09-14-03-34-589_com.termux.x11.jpg…]()

**Comment by pablo19989898** [comment]
I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc

**Comment by Pipetto-crypto** [comment]
> I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc

Mouse warp override, disable it

**Comment by pablo19989898** [comment]
> > I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc
> 
> Mouse warp override, disable it

Done that , still not works : https://www.youtube.com/watch?v=3Odocg7Txlw

**Comment by Pipetto-crypto** [comment]
> > > I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc
> > 
> > 
> > Mouse warp override, disable it
> 
> Done that , still not works : https://www.youtube.com/watch?v=3Odocg7Txlw

Not having this issue myself, I can't really fix it. I suggest to try Box compatibility preset(Configure->Box->Compatibility Preset)

**Comment by pablo19989898** [comment]
> > > > I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc
> > > 
> > > 
> > > Mouse warp override, disable it
> > 
> > 
> > Done that , still not works : https://www.youtube.com/watch?v=3Odocg7Txlw
> 
> Not having this issue myself, I can't really fix it. I suggest to try Box compatibility preset(Configure->Box->Compatibility Preset)

Not working , I also need to add that wsad not working too with cod2 , maybe it's input issue , everything works fine with oblivion.

**Comment by Pipetto-crypto** [comment]
> > > > > I tried demo too , not working. Here's is what it looks : https://www.youtube.com/watch?v=cxeB-ERRnvc
> > > > 
> > > > 
> > > > Mouse warp override, disable it
> > > 
> > > 
> > > Done that , still not works : https://www.youtube.com/watch?v=3Odocg7Txlw
> > 
> > 
> > Not having this issue myself, I can't really fix it. I suggest to try Box compatibility preset(Configure->Box->Compatibility Preset)
> 
> Not working , I also need to add that wsad not working too with cod2 , maybe it's input issue , everything works fine with oblivion.

In the future I will update the box86 and box64 in the prefix, that should fix it.

**Comment by pablo19989898** [comment]
I've solved this issue but idk how , changed alot in regs

**Comment by Pipetto-crypto** [comment]
> I've solved this issue but idk how , changed alot in regs

I will close this issue then

**Comment by pablo19989898** [comment]
So with default winebox 8.0 game works with worse performance , If I installing any mesa turnip drivers then it stops working.
