### ISSUE TITLE
[HELP] how to build box64 & box86 glibc

### ISSUE THREAD

**Issue by DevikinD** [Pipetto-crypto/3in1ProotX86Emus#12]
Help me please
I am trying to build latest box64 for glibc but not working always error

Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
wine: could not load ntdll.so: Cannot dlopen("/data/data/com.termux/files/usr/glibc/opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so"/0x5e2faaf0, 2)

wine: could not load kernel32.dll, status c0000135

build on grun --shell
patchelf used after build
`patchelf --set-interpreter /data/data/com.termux/files/usr/glibc/lib/ld-linux-aarch64.so.1 --force-rpath --set-rpath /data/data/com.termux/files/usr/glibc/lib box64`

How you build your box64 or box86?

**Comment by Pipetto-crypto** [comment]
Newer box64 don't build on grun shell anymore. You need to build them in proot

**Comment by DevikinD** [comment]
Does it need a specific patch to work? Or just need to build with Ubuntu on proot and use patchelf?

**Comment by DevikinD** [comment]
Finally, I managed to make it work properly and no error, thx bro 👍
