### ISSUE TITLE
Can´t open diplay : 0

### ISSUE THREAD

**Issue by Stogie87** [Pipetto-crypto/3in1ProotX86Emus#13]
Hi there.
I just made a clean install of termux and androBox, but if i enter androbox and then number 1, it is trying to find the correct resolution and shows "Can´t open diplay : 0".
Then it opens termux:x11, but nothing more happens. It does not start the windows desktop.

**Comment by Pipetto-crypto** [comment]
> Hi there. I just made a clean install of termux and androBox, but if i enter androbox and then number 1, it is trying to find the correct resolution and shows "Can´t open diplay : 0". Then it opens termux:x11, but nothing more happens. It does not start the windows desktop.

Have you tried with option number 2?

**Comment by Stogie87** [comment]
Yes, same result.
Using Galaxy Tab S8 with latest OneUi 5.1.1 (A13).

**Comment by Pipetto-crypto** [comment]
> Yes, same result. Using Galaxy Tab S8 with latest OneUi 5.1.1 (A13).

I wil try to patch a fix real soon

**Comment by Pipetto-crypto** [comment]
> Yes, same result. Using Galaxy Tab S8 with latest OneUi 5.1.1 (A13).

Patch pushed, next time you type androBox it should auto apply it. Then type two in terminal

**Comment by Stogie87** [comment]
Okay, thanks. Option 2 is working now, but still not option 1.
But something is different  since latest update. Direct3D seems not working anymore. No matter what i do, Cubemap either shows an error (no compatible 3D device) or it force close. It was working very well 2 days ago.

**Comment by Pipetto-crypto** [comment]
> Okay, thanks. Option 2 is working now, but still not option 1. But something is different since latest update. Direct3D seems not working anymore. No matter what i do, Cubemap either shows an error (no compatible 3D device) or it force close. It was working very well 2 days ago.

Install->Mesa->armhf->Turnip-> install the v2 option and retry

**Comment by Stogie87** [comment]
I tried Turnip v2, but Cubemap just force close.

**Comment by Pipetto-crypto** [comment]
> I tried Turnip v2, but Cubemap just force close.

Tried with dxvk?

**Comment by Stogie87** [comment]
Seems like you pushed a new update. Option 1 is also working, now.
With dxvk cubemap also force close.

**Comment by Pipetto-crypto** [comment]
> Seems like you pushed a new update. Option 1 is also working, now. With dxvk cubemap also force close.

Are you using the same wine version you were using before, if so which one?

**Comment by Stogie87** [comment]
I use wine 8.0
I just made a complete fresh install 3min ago of wine 8.14, but same problem. Seems like Direct3D is not working anymore. All tests force close and they where working 2 days ago. Also the Game i usually try (Jagged Alliance 2) only runs very slow now.

**Comment by Pipetto-crypto** [comment]
> I use wine 8.0 I just made a complete fresh install 3min ago of wine 8.14, but same problem. Seems like Direct3D is not working anymore. All tests force close and they where working 2 days ago. Also the Game i usually try (Jagged Alliance 2) only runs very slow now.

They work for me, one thing you could try if you are on the latest androBox update is to reinstall the glibc prefx and then wine from Troubleshooting page. Make sure you have a stable Internet connection

**Comment by Stogie87** [comment]
I tried troubleshooting.
Idk what the problem is. If i remove androbox-folder, wine-packages from root folder and delete data from termux all androbox files are completly removed, right? Or are there some leftover files from older installations on the device?

**Comment by Stogie87** [comment]
I think, i will give up for today. Before it was possible to launch androBox via "androBox" in terminal Direct3D was working without issues. I tried severeal clean installations, but i can not get it work again

**Comment by Stogie87** [comment]
Hi there.
I finally got it working. It was a very stupid problem on my side. I had to reinstall Termux and Termux 11 and now Direct3D is working like it should. Thanks for you support and sorry for the inconvenience...

**Comment by Pipetto-crypto** [comment]
> Hi there. I finally got it working. It was a very stupid problem on my side. I had to reinstall Termux and Termux 11 and now Direct3D is working like it should. Thanks for you support and sorry for the inconvenience...

It's okay, I will close this issue then
