### ISSUE TITLE
VirGL installation question

### ISSUE THREAD

**Issue by kimaiden1408** [Pipetto-crypto/3in1ProotX86Emus#16]
It seems able use VirGL testsever on androBox. I clicked virgl install but nothing changed. I launched gpu caps viewer but there was no gpu detected.
![Screenshot_20231115_100354_TermuxX11](https://github.com/Pipetto-crypto/androBox/assets/85208945/c241f54d-abe5-488b-869f-f9de2f95b0ff)

**Comment by Pipetto-crypto** [comment]
Virgl compatibility hasn't been added yet. And it won't be added anytime soon.

**Comment by kimaiden1408** [comment]
Oh.. ok I thought it was added because it has virgl_test_server and virgl installation button.
