### ISSUE TITLE
Nothing happens when launching winetricks gui

### ISSUE THREAD

**Issue by Asuka-pr8** [Pipetto-crypto/3in1ProotX86Emus#18]
It goes to openbox then after a few seconds returns to wine without showing anything

When I write "winetricks --gui" in terminal in openbox I get this error

CANNOT LINK EXCUTABLE "zenity": library "libicuuc.so.73" not found: needed by /data/data/com.termus/files/usr/lib/libharfbuzz-icu.so in namespace (default)

Then nothing shows.
I didn't face this before and it only happened after I cleared termux data and reinstalled androBox so I guess it's because a recent update
Also I tried to reinstall androBox a lot of times but I still get this same error

**Comment by Pipetto-crypto** [comment]
> It goes to openbox then after a few seconds returns to wine without showing anything
> 
> When I write "winetricks --gui" in terminal in openbox I get this error
> 
> CANNOT LINK EXCUTABLE "zenity": library "libicuuc.so.73" not found: needed by /data/data/com.termus/files/usr/lib/libharfbuzz-icu.so in namespace (default)
> 
> Then nothing shows. I didn't face this before and it only happened after I cleared termux data and reinstalled androBox so I guess it's because a recent update Also I tried to reinstall androBox a lot of times but I still get this same error

That library is in package libicu, if you don't have that installed, install it.

In case you can install any verb from the Tweaks option in the androBox menu directly.

**Comment by Asuka-pr8** [comment]
It's already installed
Using "pkg"
I tried reinstalling and uninstalling both it and harfbuzz-icu and zenity then installing them
Still the same error

**Comment by Pipetto-crypto** [comment]
> It's already installed Using "pkg" I tried reinstalling and uninstalling both it and harfbuzz-icu and zenity then installing them Still the same error

https://github.com/termux/termux-packages/issues/18524

The issue is not on this project side but termux side. Nothing to do, you have to wait for an update on their side

**Comment by Asuka-pr8** [comment]
I see
Well thanks for replying and giving the link for issue

**Comment by Asuka-pr8** [comment]
Its working now
I used "pkg up" and it worked
