### ISSUE TITLE
Problem with Box64 November build

### ISSUE THREAD

**Issue by aegri-somnia** [Pipetto-crypto/3in1ProotX86Emus#19]
Hi, I am facing 2 problems with box builds for November.

1.  64 bit games are not working using the November builds, 32 bit games works fine.

64 bit games shows an invalid error in 7zfm and CLI output of running a 64 bit game is shown below

<img src="https://github.com/Pipetto-crypto/androBox/assets/151121546/8979db6b-4f8b-4159-89dc-42426c6b648a" width=50% height=50%>

<br><br>
2.  Drives are missing from 7zfm in November box builds as shown in screenshots

November Build : 

<img src="https://github.com/Pipetto-crypto/androBox/assets/151121546/4d7d66fc-dc32-49d5-b0f7-aa4821040ee6" width=60% height=60%>

October Build : 

<img src="https://github.com/Pipetto-crypto/androBox/assets/151121546/8f39220b-8235-46f5-a161-d3265e47c3fe)" width=60% height=60%>

**Comment by Pipetto-crypto** [comment]
> Hi, I am facing 2 problems with box builds for November.
> 
>     1. 64 bit games are not working using the November builds, 32 bit games works fine.
> 
> 
> 64 bit games shows an invalid error in 7zfm and CLI output of running a 64 bit game is shown below
> <img alt="" width="50%" height="50%" src="https://user-images.githubusercontent.com/151121546/283709656-8979db6b-4f8b-4159-89dc-42426c6b648a.jpg">
> 
> 2. Drives are missing from 7zfm in November box builds as shown in screenshots
> 
> November Build :
> <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/151121546/283709779-4d7d66fc-dc32-49d5-b0f7-aa4821040ee6.jpg">
> 
> October Build :
> <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/151121546/283709823-8f39220b-8235-46f5-a161-d3265e47c3fe.jpg">

Just tested and it works fine on my side. I need you to enable logging from the start menu(log_level1). A log file will be created in /sdcard/androBox/box_logs

**Comment by aegri-somnia** [comment]
Here is the log file with log_level1

[logs.txt](https://github.com/Pipetto-crypto/androBox/files/13389769/logs.txt)

**Comment by Pipetto-crypto** [comment]
> Here is the log file with log_level1
> 
> [logs.txt](https://github.com/Pipetto-crypto/androBox/files/13389769/logs.txt)

Have you tried with other wine versions?

**Comment by aegri-somnia** [comment]
Yes, also tried wine 8.14 and wine 8.0 both gives same result.

**Comment by Pipetto-crypto** [comment]
> Yes, also tried wine 8.14 and wine 8.0 both gives same result.

I can't reproduce this issue on my side I am afraid, I will try to make another box64 build in the near future

**Comment by aegri-somnia** [comment]
Ok, Thank you

**Comment by aegri-somnia** [comment]
After some testing I think I was able to find the issue.

I compiled my own latest box64 build but that was giving the same problem.
So, I thought of using box64droid native to test box builds and surprisingly the new box builds were working fine in box64droid native.

Further, I tried comparing the exported variables in androBox and Box64Driod native.

I think Box64Droid native have this additional exports which are not in androBox if I have not missed anything

export BOX64_ALLOWMISSINGLIBS=1
export BOX86_ALLOWMISSINGLIBS=1

But the interesting thing is,

If I do not export these MISSINGLIBS variables some 32 bit games that did not work before starts working but 64 bit games stops working and 7zfm does not show drives.

And if I export above MISSINGLIBS variables then androBox and box64droid native shows same behavior but some 32 bit games stop working which work if we do not export MISSINGLIBS.

It could be a driver issue may be since I have an adreno 725 or could be box issue.

Note : All above testing was done using November builds of box64 and box86.

**Comment by Pipetto-crypto** [comment]
> After some testing I think I was able to find the issue.
> 
> I compiled my own latest box64 build but that was giving the same problem. So, I thought of using box64droid native to test box builds and surprisingly the new box builds were working fine in box64droid native.
> 
> Further, I tried comparing the exported variables in androBox and Box64Driod native.
> 
> I think Box64Droid native have this additional exports which are not in androBox if I have not missed anything
> 
> export BOX64_ALLOWMISSINGLIBS=1 export BOX86_ALLOWMISSINGLIBS=1
> 
> But the interesting thing is,
> 
> If I do not export these MISSINGLIBS variables some 32 bit games that did not work before starts working but 64 bit games stops working and 7zfm does not show drives.
> 
> And if I export above MISSINGLIBS variables then androBox and box64droid native shows same behavior but some 32 bit games stop working which work if we do not export MISSINGLIBS.
> 
> It could be a driver issue may be since I have an adreno 725 or could be box issue.
> 
> Note : All above testing was done using November builds of box64 and box86.

I don't know which games you were trying but gstreamer games are not supported for now.

**Comment by aegri-somnia** [comment]
I see.
Since, everything is fine on my side now, I will close the issue.
