### ISSUE TITLE
Error Can't run Box64

### ISSUE THREAD

**Issue by wand09** [Pipetto-crypto/3in1ProotX86Emus#2]
I've tried re-installing several times, but an error always occurs.  and switch to box86 which has poor performance.  This happens with new code/script updates.  because when I first installed it two days ago, there were no problems like this

Like this
![IMG_20231102_085301_168](https://github.com/Pipetto-crypto/androBox/assets/39123207/99f92f68-7d5e-474e-b197-614ad6afb5f0)

**Comment by wand09** [comment]
![IMG_20231102_085301_168](https://github.com/Pipetto-crypto/androBox/assets/39123207/ea936df4-51d9-4c17-841d-21850e44320f)


Like this

**Comment by Pipetto-crypto** [comment]
That's not an error. It's normal since wine being a x86 program gets launched with box86, when you use x64 programs instead they get launched with box64

**Comment by Luihart** [comment]
Open X11 App and you will See it wants to Install Mono Installer.

**Comment by wand09** [comment]
> That's not an error. It's normal since wine being a x86 program gets launched with box86, when you use x64 programs instead they get launched with box64

three days ago it had good performance, but now it has very bad.  what's wrong?
