### ISSUE TITLE
termux closes after 5 minutes

### ISSUE THREAD

**Issue by Oscar1640** [Pipetto-crypto/3in1ProotX86Emus#20]
Device : redmi 12C
Ram: 3 GB
SoC: mediatek helio G85
Android version: android 12

Everything starts perfectly but after a few minutes the termux application in the background closes.
This problem does not happen to me with exagear or with winlator.

**Comment by Oscar1640** [comment]
Hello, I realized that only mesa turnip is available.
Is there a way to use virgl or llvm as rendering for those of us who don't have a snapdragon chipset?
note: I managed to solve the above problem by activating the autostart permission for termux.
and disabling the ghost process killer as indicated here
https://github.com/HardcodedCat/termux-monet#phantom-process-killer

**Comment by Pipetto-crypto** [comment]
> Hello, I realized that only mesa turnip is available. Is there a way to use virgl or llvm as rendering for those of us who don't have a snapdragon chipset? note: I managed to solve the above problem by activating the autostart permission for termux. and disabling the ghost process killer as indicated here https://github.com/HardcodedCat/termux-monet#phantom-process-killer

Mali is not supported for now. But it should be supported soonish. If you solved this issue then, I can close this.
