### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by YSF744** [Pipetto-crypto/3in1ProotX86Emus#22]
How to uninstall androbox?

**Comment by Pipetto-crypto** [comment]
By wiping Termux data.

**Comment by YSF744** [comment]
thanks for the reply but unfourtunely I have other things installed in termux so if there is another way to uninstall without I would appreciate it if not I will just wipe termux data

**Comment by Pipetto-crypto** [comment]
I will add a way to uninstall then. I will let you know when it's added.

Il mer 22 nov 2023, 13:06 YSF744 ***@***.***> ha scritto:

**Comment by YSF744** [comment]
ok thanks
