### ISSUE TITLE
DXVK not working

### ISSUE THREAD

**Issue by NitroGear504** [Pipetto-crypto/3in1ProotX86Emus#3]
I've tried to install dxvk, but when trying to launch Cube Map, it shows me this:
![Screenshot_20231102-163228_Termux_X11](https://github.com/Pipetto-crypto/androBox/assets/68450462/5570fc39-cd04-4e8f-9d48-57836bd052d0)

**Comment by Pipetto-crypto** [comment]
Which GPU do you have? Right now only Adreno are supported

**Comment by NitroGear504** [comment]
> Which GPU do you have? Right now only Adreno are supported

Adreno 610

**Comment by Pipetto-crypto** [comment]
I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:

Update-Prefix
Install->Mesa->armhf->Turnip->turnip_10.30.23v2 

Retry the dx9 demo

**Comment by NitroGear504** [comment]
> I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> 
> Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> 
> Retry the dx9 demo

Sure

**Comment by NitroGear504** [comment]
> I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> 
> Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> 
> Retry the dx9 demo

Still not working

**Comment by Pipetto-crypto** [comment]
> > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > Retry the dx9 demo
> 
> Still not working

Try with another version of dxvk like 2.2 or 1.10.3

**Comment by NitroGear504** [comment]
### 

> > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > Retry the dx9 demo
> > 
> > 
> > Still not working
> 
> Try with another version of dxvk like 2.2 or 1.10.3

I already did that, but it still doesn't work

**Comment by Pipetto-crypto** [comment]
> > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > Retry the dx9 demo
> > > 
> > > 
> > > Still not working
> > 
> > 
> > Try with another version of dxvk like 2.2 or 1.10.3
> 
> I already did that, but it still doesn't work

Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?

**Comment by NitroGear504** [comment]
> > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > Retry the dx9 demo
> > > > 
> > > > 
> > > > Still not working
> > > 
> > > 
> > > Try with another version of dxvk like 2.2 or 1.10.3
> > 
> > 
> > I already did that, but it still doesn't work
> 
> Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?

Yes, both running

**Comment by Pipetto-crypto** [comment]
> > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > Retry the dx9 demo
> > > > > 
> > > > > 
> > > > > Still not working
> > > > 
> > > > 
> > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > 
> > > 
> > > I already did that, but it still doesn't work
> > 
> > 
> > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> 
> Yes, both running

Does turnip appears there?

**Comment by NitroGear504** [comment]
> > > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > > Retry the dx9 demo
> > > > > > 
> > > > > > 
> > > > > > Still not working
> > > > > 
> > > > > 
> > > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > > 
> > > > 
> > > > I already did that, but it still doesn't work
> > > 
> > > 
> > > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> > 
> > 
> > Yes, both running
> 
> Does turnip appears there?

No, it doesn't appear

**Comment by Pipetto-crypto** [comment]
> > > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > > Retry the dx9 demo
> > > > > > 
> > > > > > 
> > > > > > Still not working
> > > > > 
> > > > > 
> > > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > > 
> > > > 
> > > > I already did that, but it still doesn't work
> > > 
> > > 
> > > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> > 
> > 
> > Yes, both running
> 
> Does turnip appears there?

What Android version do you have?

**Comment by NitroGear504** [comment]
> > > > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > > > Retry the dx9 demo
> > > > > > > 
> > > > > > > 
> > > > > > > Still not working
> > > > > > 
> > > > > > 
> > > > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > > > 
> > > > > 
> > > > > I already did that, but it still doesn't work
> > > > 
> > > > 
> > > > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> > > 
> > > 
> > > Yes, both running
> > 
> > 
> > Does turnip appears there?
> 
> What Android version do you have?

13

**Comment by Pipetto-crypto** [comment]
> > > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > > Retry the dx9 demo
> > > > > > 
> > > > > > 
> > > > > > Still not working
> > > > > 
> > > > > 
> > > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > > 
> > > > 
> > > > I already did that, but it still doesn't work
> > > 
> > > 
> > > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> > 
> > 
> > Yes, both running
> 
> Does turnip appears there?

What Android version do you have? 

> > > > > > > > > I am not sure that GPU is supported in upstream Mesa. Could you try to update and install turnip_10.30.23v2 with these commands:
> > > > > > > > > Update-Prefix Install->Mesa->armhf->Turnip->turnip_10.30.23v2
> > > > > > > > > Retry the dx9 demo
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Still not working
> > > > > > > 
> > > > > > > 
> > > > > > > Try with another version of dxvk like 2.2 or 1.10.3
> > > > > > 
> > > > > > 
> > > > > > I already did that, but it still doesn't work
> > > > > 
> > > > > 
> > > > > Update again from Start Menu (Update->Prefix) and try to launch both DXCapsViewers in GraphicsTests, do they run?
> > > > 
> > > > 
> > > > Yes, both running
> > > 
> > > 
> > > Does turnip appears there?
> > 
> > 
> > What Android version do you have?
> 
> 13

I will control if mesa upstream has A610 support then I will make another turnip

**Comment by Luihart** [comment]
He needs to make Sure to use Zink renderer. It seems virGL is Set as Default, because at First FPS hud of wined3d appeared in 3d test

**Comment by Pipetto-crypto** [comment]
> He needs to make Sure to use Zink renderer. It seems virGL is Set as Default, because at First FPS hud of wined3d appeared in 3d test

There is no virgl, it's not enabled and you can't switch renderer yet. It forces Zink

**Comment by NitroGear504** [comment]
Ok, it worked now. Thanks man.
