### ISSUE TITLE
AndroBox Cannot install

### ISSUE THREAD

**Issue by Muzsyam** [Pipetto-crypto/3in1ProotX86Emus#33]
Im stuck while trying to install androbox
![Screenshot_2024-01-28-20-12-40-250_com termux](https://github.com/Pipetto-crypto/androBox/assets/157964097/a87376fc-d596-4795-8e96-fd132a3ff912)

**Comment by Pipetto-crypto** [comment]
Post the log here

**Comment by Asuka-pr8** [comment]
[setup_log.txt](https://github.com/Pipetto-crypto/androBox/files/14076482/setup_log.txt)

When upgrading some packages ask if you want to keep current or use latest and it doesn't show in termux but you can answer them blindly.

**Comment by Pipetto-crypto** [comment]
> [setup_log.txt](https://github.com/Pipetto-crypto/androBox/files/14076482/setup_log.txt)
> 
> When upgrading some packages ask if you want to keep current or use latest and it doesn't show in termux but you can answer them blindly.

Ok, I pushed a fix

**Comment by Muzsyam** [comment]
Tq its work now 🙏 thanks Pipetto-crypto and
Also thanks asuka for helping me
