### ISSUE TITLE
I don't know but performance is very low

### ISSUE THREAD

**Issue by Saikatsaha1996** [Pipetto-crypto/3in1ProotX86Emus#5]
In Androbox I am getting..
![Screenshot_2023-11-03-00-58-17-51_00df01c412509efb9bd6450c382822af](https://github.com/Pipetto-crypto/androBox/assets/72664192/f5e2ff5d-dfbd-4dde-85fe-36b69e0318bd)

I actually getting (not Androbox)
![IMG_20231101_045715](https://github.com/Pipetto-crypto/androBox/assets/72664192/02a55e09-bc3b-4f69-a41a-c26dc95244a1)

**Comment by Pipetto-crypto** [comment]
I enable vsync by default to avoid issues with flickers and jitter

**Comment by wand09** [comment]
> I enable vsync by default to avoid issues with flickers and jitter

Can be disable?

**Comment by Saikatsaha1996** [comment]
> I enable vsync by default to avoid issues with flickers and jitter

Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..

I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed...  via winetricks dx9 unable to install..

**Comment by Pipetto-crypto** [comment]
> > I enable vsync by default to avoid issues with flickers and jitter
> 
> Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> 
> I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..

dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:

Update->Prefix and retry

**Comment by Saikatsaha1996** [comment]
> > > I enable vsync by default to avoid issues with flickers and jitter
> > 
> > 
> > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> 
> dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> 
> Update->Prefix and retry

I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..

**Comment by Pipetto-crypto** [comment]
> > > > I enable vsync by default to avoid issues with flickers and jitter
> > > 
> > > 
> > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > 
> > 
> > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > Update->Prefix and retry
> 
> I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..

dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet

**Comment by Saikatsaha1996** [comment]
> > > > > I enable vsync by default to avoid issues with flickers and jitter
> > > > 
> > > > 
> > > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > > 
> > > 
> > > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > > Update->Prefix and retry
> > 
> > 
> > I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..
> 
> dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet

Okay okay.. so my favourite game won't work if dxdiag.exe unable to open..

Because in proot when I was installed box & wine manually I also was same issues but I was installed gstreamer .. and then I installed directx9 via winetricks & then I finally opened dxdiag.exe & also game started..

Just installed wine devel
```
grep: /data/data/com.termux/files/home/.androBox: No such file or directory                                                         /data/data/com.termux/files/usr/bin/wine: line 95: [: ==: unary operator expected
Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
wine: could not load kernel32.dll, status c0000135
```

**Comment by Pipetto-crypto** [comment]
> > > > > > I enable vsync by default to avoid issues with flickers and jitter
> > > > > 
> > > > > 
> > > > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > > > 
> > > > 
> > > > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > > > Update->Prefix and retry
> > > 
> > > 
> > > I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..
> > 
> > 
> > dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet
> 
> Okay okay.. so my favourite game won't work if dxdiag.exe unable to open..
> 
> Because in proot when I was installed box & wine manually I also was same issues but I was installed gstreamer .. and then I installed directx9 via winetricks & then I finally opened dxdiag.exe & also game started..
> 
> Just installed wine devel
> 
> ```
> grep: /data/data/com.termux/files/home/.androBox: No such file or directory                                                         /data/data/com.termux/files/usr/bin/wine: line 95: [: ==: unary operator expected
> Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
> wine: could not load kernel32.dll, status c0000135
> ```

I will add those libraries soon

**Comment by Pipetto-crypto** [comment]
> > > > > > I enable vsync by default to avoid issues with flickers and jitter
> > > > > 
> > > > > 
> > > > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > > > 
> > > > 
> > > > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > > > Update->Prefix and retry
> > > 
> > > 
> > > I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..
> > 
> > 
> > dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet
> 
> Okay okay.. so my favourite game won't work if dxdiag.exe unable to open..
> 
> Because in proot when I was installed box & wine manually I also was same issues but I was installed gstreamer .. and then I installed directx9 via winetricks & then I finally opened dxdiag.exe & also game started..
> 
> Just installed wine devel
> 
> ```
> grep: /data/data/com.termux/files/home/.androBox: No such file or directory                                                         /data/data/com.termux/files/usr/bin/wine: line 95: [: ==: unary operator expected
> Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
> wine: could not load kernel32.dll, status c0000135
> ```

How did you change to wine devel? This process should have be done from Start Menu

**Comment by Saikatsaha1996** [comment]
> > > > > > > I enable vsync by default to avoid issues with flickers and jitter
> > > > > > 
> > > > > > 
> > > > > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > > > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > > > > 
> > > > > 
> > > > > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > > > > Update->Prefix and retry
> > > > 
> > > > 
> > > > I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..
> > > 
> > > 
> > > dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet
> > 
> > 
> > Okay okay.. so my favourite game won't work if dxdiag.exe unable to open..
> > Because in proot when I was installed box & wine manually I also was same issues but I was installed gstreamer .. and then I installed directx9 via winetricks & then I finally opened dxdiag.exe & also game started..
> > Just installed wine devel
> > ```
> > grep: /data/data/com.termux/files/home/.androBox: No such file or directory                                                         /data/data/com.termux/files/usr/bin/wine: line 95: [: ==: unary operator expected
> > Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
> > wine: could not load kernel32.dll, status c0000135
> > ```
> 
> How did you change to wine devel? This process should have be done from Start Menu

Full fresh installed when asked for wine version I choose wine devel

**Comment by aaa-sys-potato** [comment]
Sorry for bother bro but I have somethings to tell you... androBox it's now supported mali so...Can you add the option of opengl 2.1 and opengl 3.3 to choose between? Because if you have Virgil and click or something like that OpenGL 3.3, you will be able to run DirectX 11 games so.... Can you do that please?

**Comment by Pipetto-crypto** [comment]
> Sorry for bother bro but I have somethings to tell you... androBox it's now supported mali so...Can you add the option of opengl 2.1 and opengl 3.3 to choose between? Because if you have Virgil and click or something like that OpenGL 3.3, you will be able to run DirectX 11 games so.... Can you do that please?

It doesn't support Mali yet. If Mali are running is through llvmpipe which should be the fallback when no zink is detected. Mali support will come a bit later than expected

**Comment by aaa-sys-potato** [comment]
> > Sorry for bother bro but I have somethings to tell you... androBox it's now supported mali so...Can you add the option of opengl 2.1 and opengl 3.3 to choose between? Because if you have Virgil and click or something like that OpenGL 3.3, you will be able to run DirectX 11 games so.... Can you do that please?
> 
> It doesn't support Mali yet. If Mali are running is through llvmpipe which should be the fallback when no zink is detected. Mali support will come a bit later than expected

Oh, that's why there's no mesa for virgil... alright bro If it is or will be supported mali just tell me  (: I will do some tests for now

**Comment by Pipetto-crypto** [comment]
> > > > > > > > I enable vsync by default to avoid issues with flickers and jitter
> > > > > > > 
> > > > > > > 
> > > > > > > Okay.. it's vsync nice & it's actually real fps which I can get inside games.. I have to check in game.. I only play openrail.. which required `dxdiag.exe` ..
> > > > > > > I tried to run `dxdiag` it's not working.. but it's workers if I installed `dx9` via `winetricks.` But `winetricks` crashed... via winetricks dx9 unable to install..
> > > > > > 
> > > > > > 
> > > > > > dx9 can be installed from Install->Tweaks. Try from there and in case it doesn't work do:
> > > > > > Update->Prefix and retry
> > > > > 
> > > > > 
> > > > > I will update.. but I think with that way dxdiag.exe will won't open.. but let's see & will update you..
> > > > 
> > > > 
> > > > dxdiag.exe indeed won't open for now since it requires gstreamer libraries which I have not put yet
> > > 
> > > 
> > > Okay okay.. so my favourite game won't work if dxdiag.exe unable to open..
> > > Because in proot when I was installed box & wine manually I also was same issues but I was installed gstreamer .. and then I installed directx9 via winetricks & then I finally opened dxdiag.exe & also game started..
> > > Just installed wine devel
> > > ```
> > > grep: /data/data/com.termux/files/home/.androBox: No such file or directory                                                         /data/data/com.termux/files/usr/bin/wine: line 95: [: ==: unary operator expected
> > > Error: reading elf header of /data/data/com.termux/files/usr/glibc/opt/wine/bin/wine, try to launch using box86 instead
> > > wine: could not load kernel32.dll, status c0000135
> > > ```
> > 
> > 
> > How did you change to wine devel? This process should have be done from Start Menu
> 
> Full fresh installed when asked for wine version I choose wine devel

I added an option to reinstall in setup.sh script. Just copy paste the new command in the readme and make sure you have a stable connection. Also I got dxdiag working after installing it from winetricks using dxdiag voice though I had to download manually a file since some links are dead. Installing dx9 from winetricks didn't do anything at all.

**Comment by aaa-sys-potato** [comment]
![Screenshot_20231104_111638_TermuxX11](https://github.com/Pipetto-crypto/androBox/assets/149486964/7768c117-4ec0-4c33-98e0-42c079e60f21)


Oh bro that's so no... opengl 1.1? That's so bad for virgil It almost doesn't work any game. Please fix it and sorry for bother again bro (: I just like your emulator 😃 and what I mean (please fix it) I mean make it opengl 3.3 or something like that

**Comment by hrachkovinovoto** [comment]
@Pipetto-crypto, do you plan on eventually implementing dri3 turnip? Contrary to what is being mentioned in this topic, I am actually getting decent performance on a Snapdragon 870, and I imagine it will be even better once dri3 is added.

**Comment by Pipetto-crypto** [comment]
> @Pipetto-crypto, do you plan on eventually implementing dri3 turnip? Contrary to what is being mentioned in this topic, I am actually getting decent performance on a Snapdragon 870, and I imagine it will be even better once dri3 is added.

The turnip I am using it's already dri3

**Comment by wand09** [comment]
> > @Pipetto-crypto, do you plan on eventually implementing dri3 turnip? Contrary to what is being mentioned in this topic, I am actually getting decent performance on a Snapdragon 870, and I imagine it will be even better once dri3 is added.
> 
> The turnip I am using it's already dri3

is it possible to make androbox access all folder in Android/data ?  in termux-box Drive E: will point to Android/data/ but only folder com.termux

**Comment by Pipetto-crypto** [comment]
> > > @Pipetto-crypto, do you plan on eventually implementing dri3 turnip? Contrary to what is being mentioned in this topic, I am actually getting decent performance on a Snapdragon 870, and I imagine it will be even better once dri3 is added.
> > 
> > 
> > The turnip I am using it's already dri3
> 
> is it possible to make androbox access all folder in Android/data ? in termux-box Drive E: will point to Android/data/ but only folder com.termux

Because how Android works it is not possible without root but I can make Termux data folder accessible

**Comment by Saikatsaha1996** [comment]
Unable to run Androbox
![Screenshot_2024-01-04-22-34-38-22_84d3000e3f4017145260f7618db1d683](https://github.com/Pipetto-crypto/androBox/assets/72664192/093fa525-93ba-41fd-aa9d-f4c0117f0b37)
