### ISSUE TITLE
Failed update prfx

### ISSUE THREAD

**Issue by wand09** [Pipetto-crypto/3in1ProotX86Emus#6]
Hello bro, can you make a option re-install glibc_prefix.tar.xz  via termux without clear all data/Cache? 
I had connection problems while updating prefix, and couldn't boot on termux11.

![Screenshot_2023-11-03-10-00-47-452_com termux](https://github.com/Pipetto-crypto/androBox/assets/39123207/f3d6a7d6-b495-4f17-ac3f-5fd412792a4e)

**Comment by Pipetto-crypto** [comment]
> Hello bro, can you make a option re-install glibc_prefix.tar.gz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> 
> ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)

I will add an option to reinstall to the setup.sh script

**Comment by wand09** [comment]
> > Hello bro, can you make a option re-install glibc_prefix.tar.gz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> 
> I will add an option to reinstall to the setup.sh script

how to do it?  did enter the installation command?

**Comment by wand09** [comment]
> > Hello bro, can you make a option re-install glibc_prefix.tar.gz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> 
> I will add an option to reinstall to the setup.sh script

thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite

**Comment by Pipetto-crypto** [comment]
> > > Hello bro, can you make a option re-install glibc_prefix.tar.gz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > 
> > 
> > I will add an option to reinstall to the setup.sh script
> 
> thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite

rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh

The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.

**Comment by wand09** [comment]
> > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > 
> > > 
> > > I will add an option to reinstall to the setup.sh script
> > 
> > 
> > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> 
> rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> 
> The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.

When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?

**Comment by Pipetto-crypto** [comment]
> > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > 
> > > > 
> > > > I will add an option to reinstall to the setup.sh script
> > > 
> > > 
> > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > 
> > 
> > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> 
> When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?

It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer

**Comment by wand09** [comment]
> > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > 
> > > > > 
> > > > > I will add an option to reinstall to the setup.sh script
> > > > 
> > > > 
> > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > 
> > > 
> > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > 
> > 
> > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> 
> It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer

Ok bro

Btw after new installation, why can't open any program after installing Dxvk/async ?

**Comment by Pipetto-crypto** [comment]
> > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > 
> > > > > > 
> > > > > > I will add an option to reinstall to the setup.sh script
> > > > > 
> > > > > 
> > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > 
> > > > 
> > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > 
> > > 
> > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > 
> > 
> > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> 
> Ok bro
> 
> Btw after new installation, why can't open any program after installing Dxvk/async ?

Which wine version are you using and what GPU do you have?

**Comment by wand09** [comment]
> > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > 
> > > > > 
> > > > > I will add an option to reinstall to the setup.sh script
> > > > 
> > > > 
> > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > 
> > > 
> > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > 
> > 
> > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> 
> It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer

All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.

There was no problem like this before,

**Comment by wand09** [comment]
> > > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > I will add an option to reinstall to the setup.sh script
> > > > > > 
> > > > > > 
> > > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > > 
> > > > > 
> > > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > > 
> > > > 
> > > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > > 
> > > 
> > > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> > 
> > 
> > Ok bro
> > Btw after new installation, why can't open any program after installing Dxvk/async ?
> 
> Which wine version are you using and what GPU do you have?

Wine 8.14 device pocox3p android 13, gpu a640

**Comment by Pipetto-crypto** [comment]
> > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > 
> > > > > > 
> > > > > > I will add an option to reinstall to the setup.sh script
> > > > > 
> > > > > 
> > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > 
> > > > 
> > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > 
> > > 
> > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > 
> > 
> > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> 
> All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.
> 
> There was no problem like this before,

Install->Mesa->armhf->Turnip and try the v2 version

**Comment by wand09** [comment]
> > > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > I will add an option to reinstall to the setup.sh script
> > > > > > 
> > > > > > 
> > > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > > 
> > > > > 
> > > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > > 
> > > > 
> > > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > > 
> > > 
> > > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> > 
> > 
> > All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.
> > There was no problem like this before,
> 
> Install->Mesa->armhf->Turnip and try the v2 version

Can't download automatically, is there a link to download manually?

**Comment by Pipetto-crypto** [comment]
> > > > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I will add an option to reinstall to the setup.sh script
> > > > > > > 
> > > > > > > 
> > > > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > > > 
> > > > > > 
> > > > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > > > 
> > > > > 
> > > > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > > > 
> > > > 
> > > > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> > > 
> > > 
> > > All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.
> > > There was no problem like this before,
> > 
> > 
> > Install->Mesa->armhf->Turnip and try the v2 version
> 
> Can't download automatically, is there a link to download manually?

It's in the Start Menu, if you press on it, it will download automatically and install. Do you have any error?

**Comment by wand09** [comment]
> > > > > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I will add an option to reinstall to the setup.sh script
> > > > > > > > 
> > > > > > > > 
> > > > > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > > > > 
> > > > > > > 
> > > > > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > > > > 
> > > > > > 
> > > > > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > > > > 
> > > > > 
> > > > > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> > > > 
> > > > 
> > > > All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.
> > > > There was no problem like this before,
> > > 
> > > 
> > > Install->Mesa->armhf->Turnip and try the v2 version
> > 
> > 
> > Can't download automatically, is there a link to download manually?
> 
> It's in the Start Menu, if you press on it, it will download automatically and install. Do you have any error?

now it works, thanks for you help.  has a bad connection, it is quite difficult to connect the server

btw, is Androbox supported Dri3?

**Comment by Pipetto-crypto** [comment]
> > > > > > > > > > > Hello bro, can you make a option re-install glibc_prefix.tar.xz via termux without clear all data/Cache? I had connection problems while updating prefix, and couldn't boot on termux11.
> > > > > > > > > > > ![Screenshot_2023-11-03-10-00-47-452_com termux](https://user-images.githubusercontent.com/39123207/280176416-f3d6a7d6-b495-4f17-ac3f-5fd412792a4e.jpg)
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I will add an option to reinstall to the setup.sh script
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > thank you bro, btw will reinstallation duplicate the data from the previous installation? Or ovrwrite
> > > > > > > > 
> > > > > > > > 
> > > > > > > > rm -rf $HOME/setup.sh && curl -L https://raw.githubusercontent.com/Pipetto-crypto/androBox/androBoxNew/setup.sh -O && source setup.sh
> > > > > > > > The reinstallation should overwrite existing data, you just need to type "2" when prompted. If you want to switch wine, you can do it from the start menu shortcut.
> > > > > > > 
> > > > > > > 
> > > > > > > When selecting the re-install option, why delete the glibc.tar.gz file on the SD card and re-download it?
> > > > > > 
> > > > > > 
> > > > > > It's safe to do so in case some files didn't download properly from previous installation, in the future I will add sha1sum checks but right now I am working on gstreamer
> > > > > 
> > > > > 
> > > > > All programs that require DX now cannot be opened, the process will disappear in taskmg immediately.
> > > > > There was no problem like this before,
> > > > 
> > > > 
> > > > Install->Mesa->armhf->Turnip and try the v2 version
> > > 
> > > 
> > > Can't download automatically, is there a link to download manually?
> > 
> > 
> > It's in the Start Menu, if you press on it, it will download automatically and install. Do you have any error?
> 
> now it works, thanks for you help. has a bad connection, it is quite difficult to connect the server
> 
> btw, is Androbox supported Dri3?

Yes, it supports dri3, but these Turnip I shipped seem to have issues with freezing and jittering. I have figured out what the problem is and I will compile new Turnip soon between Saturday, Sunday and Monday
