### ISSUE TITLE
Affinity core

### ISSUE THREAD

**Issue by wand09** [Pipetto-crypto/3in1ProotX86Emus#8]
Can you add set affinity core option on termux ?

Always set as in the pict, have slow performance

![Uploading IMG_20231104_183631.jpg…]()

**Comment by Pipetto-crypto** [comment]
I can't see the picture but it is already there, if you update it sets the core affinity to 4-7

**Comment by wand09** [comment]
> I can't see the picture but it is already there, if you update it sets the core affinity to 4-7

![Uploading Screenshot_2023-11-04-17-50-28-825_com.termux.x11.jpg…]()

Always like this

**Comment by wand09** [comment]
> I can't see the picture but it is already there, if you update it sets the core affinity to 4-7

Its always set only 4, and can't set 6-7

**Comment by Pipetto-crypto** [comment]
> > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> 
> Its always set only 4, and can't set 6-7

Have you updated?

**Comment by wand09** [comment]
> > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > 
> > 
> > Its always set only 4, and can't set 6-7
> 
> Have you updated?

Yes, latest

**Comment by Pipetto-crypto** [comment]
> > > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > > 
> > > 
> > > Its always set only 4, and can't set 6-7
> > 
> > 
> > Have you updated?
> 
> Yes, latest

Some manufactures have blocked taskset from working properly but I have come up with a solution:

You see the task manager process in the system tray, open it. It's a program called ProcessLasso.

Right click on services.exe, explorer.exe and 7zFM.exe and set CPU Affinity->Always->Select CPU Affinity

**Comment by wand09** [comment]
> > > > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > > > 
> > > > 
> > > > Its always set only 4, and can't set 6-7
> > > 
> > > 
> > > Have you updated?
> > 
> > 
> > Yes, latest
> 
> Some manufactures have blocked taskset from working properly but I have come up with a solution:
> 
> You see the task manager process in the system tray, open it. It's a program called ProcessLasso.
> 
> Right click on services.exe, explorer.exe and 7zFM.exe and set CPU Affinity->Always->Select CPU Affinity

thanks for the answer bro, btw why when disable service, all the disc disappear? 

And can you make imputbtidge auto launch when starting like proseslasso ?

**Comment by Pipetto-crypto** [comment]
> > > > > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > > > > 
> > > > > 
> > > > > Its always set only 4, and can't set 6-7
> > > > 
> > > > 
> > > > Have you updated?
> > > 
> > > 
> > > Yes, latest
> > 
> > 
> > Some manufactures have blocked taskset from working properly but I have come up with a solution:
> > You see the task manager process in the system tray, open it. It's a program called ProcessLasso.
> > Right click on services.exe, explorer.exe and 7zFM.exe and set CPU Affinity->Always->Select CPU Affinity
> 
> thanks for the answer bro, btw why when disable service, all the disc disappear?
> 
> And can you make imputbtidge auto launch when starting like proseslasso ?

I will investigate the issue with the disk drives, also yes I will make ib autostart in the next update

**Comment by Pipetto-crypto** [comment]
> > > > > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > > > > 
> > > > > 
> > > > > Its always set only 4, and can't set 6-7
> > > > 
> > > > 
> > > > Have you updated?
> > > 
> > > 
> > > Yes, latest
> > 
> > 
> > Some manufactures have blocked taskset from working properly but I have come up with a solution:
> > You see the task manager process in the system tray, open it. It's a program called ProcessLasso.
> > Right click on services.exe, explorer.exe and 7zFM.exe and set CPU Affinity->Always->Select CPU Affinity
> 
> thanks for the answer bro, btw why when disable service, all the disc disappear?
> 
> And can you make imputbtidge auto launch when starting like proseslasso ?

Done, update manually (Update->Prefix) if you are from an older version else it will auto-update itself.

**Comment by wand09** [comment]
> > > > > > > I can't see the picture but it is already there, if you update it sets the core affinity to 4-7
> > > > > > 
> > > > > > 
> > > > > > Its always set only 4, and can't set 6-7
> > > > > 
> > > > > 
> > > > > Have you updated?
> > > > 
> > > > 
> > > > Yes, latest
> > > 
> > > 
> > > Some manufactures have blocked taskset from working properly but I have come up with a solution:
> > > You see the task manager process in the system tray, open it. It's a program called ProcessLasso.
> > > Right click on services.exe, explorer.exe and 7zFM.exe and set CPU Affinity->Always->Select CPU Affinity
> > 
> > 
> > thanks for the answer bro, btw why when disable service, all the disc disappear?
> > And can you make imputbtidge auto launch when starting like proseslasso ?
> 
> Done, update manually (Update->Prefix) if you are from an older version else it will auto-update itself.

Thanks bro 👍👍
